#!/usr/bin/env node
/**
 * Builds design tokens with Style Dictionary.
 *
 * The build exits successfully (and loudly) when `src/` holds no token files,
 * so the pipeline is safe to run in CI before any token exists.
 */
import { readdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import StyleDictionary from 'style-dictionary';

import config from '../style-dictionary.config.js';
import { formats } from './formats.mjs';
import { typographyFormats } from './formats-typography.mjs';
import { copyFontsAction } from './actions.mjs';
import { transforms } from './transforms.mjs';

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const sourceRoot = resolve(packageRoot, 'src');

async function hasTokenSources() {
  const entries = await readdir(sourceRoot, { recursive: true, withFileTypes: true });
  return entries.some((entry) => entry.isFile() && entry.name.endsWith('.json'));
}

function register() {
  for (const transform of transforms) StyleDictionary.registerTransform(transform);
  for (const format of [...formats, ...typographyFormats]) StyleDictionary.registerFormat(format);
  StyleDictionary.registerAction(copyFontsAction);

  StyleDictionary.registerFileHeader({
    name: 'uh/header',
    fileHeader: () => [
      'UmrahHaji Design System',
      'Generated by Style Dictionary from packages/tokens/src/tokens.json.',
      'Do not edit this file directly - edit the source and run `pnpm build`.',
    ],
  });
}

async function main() {
  process.chdir(packageRoot);

  if (!(await hasTokenSources())) {
    console.log('[tokens] No token sources found in src/ - nothing to build yet.');
    return;
  }

  register();

  const sd = new StyleDictionary(config);
  await sd.hasInitialized;
  await sd.buildAllPlatforms();

  console.log('[tokens] Build complete.');
}

main().catch((error) => {
  console.error('[tokens] Build failed.');
  console.error(error);
  process.exitCode = 1;
});
